apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170754267
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/mobjrjbs-tenant/test-app-170754267/java-quarkus-170754267@sha256:4e3246c26b3b895062499a5ca85c1d4addf35a6189fd1e7b70b1f379679490f6
        name: my-java-quarkus
        resources: {}
status: {}
