apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170754267
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170754267
    app.kubernetes.io/part-of: test-app-170754267
  name: java-quarkus-170754267
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170754267
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170754267
    spec:
      containers:
      - image: quay.io/hacdev/mobjrjbs-tenant/test-app-170754267/java-quarkus-170754267@sha256:4e3246c26b3b895062499a5ca85c1d4addf35a6189fd1e7b70b1f379679490f6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
